seed: 42
env: ALE/Breakout-v5
n_envs: 8

# Preprocessing
frame_skip: 4
screen_size: 84

# Training
total_steps: 10_000_000
batch_size: 32
gamma: 0.99
start_epsilon: 1.0
end_epsilon: 0.01
exploration_fraction: 0.1
learning_rate: 1e-4
learning_starts: 80_000
train_freq: 4
tau: 1.0
target_update_freq: 1000

# Replay buffer
buffer_size: 1_000_000

# Logging
log_interval: 100

# Evaluation
eval_steps: 100_000

# Wandb
wandb:
  enabled: true
  project: visionary
